name: Build

permissions:
  contents: read
  id-token: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.6

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install pipx
          pipx ensurepath
          pipx install poetry

      - name: set up backend
        run: |
          cd backend && poetry install --with dev --with nlp --with generative
          make test

      - name: set up shared
        run: |
          cd shared && poetry install --with dev
          make test

  build_syntactical_analysis_docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::246770851643:role/github-actions
          aws-region: eu-central-1

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.6

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install pipx
          pipx ensurepath
          pipx install poetry

      - name: Build syntactical_analysis docker image for dev
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          pushd backend
          ./docker-util.sh build syntactical_analysis
          ./docker-util.sh push syntactical_analysis dev
          ./docker-util.sh push syntactical_analysis prod
    
  build_inflection_docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::246770851643:role/github-actions
          aws-region: eu-central-1

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.6

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install pipx
          pipx ensurepath
          pipx install poetry

      - name: Build syntactical_analysis docker image for dev
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          pushd backend
          ./docker-util.sh build inflection
          ./docker-util.sh push inflection dev

  deploy_dev_infrastructure:
    needs: [build_syntactical_analysis_docker, build_inflection_docker]
    runs-on: ubuntu-latest
    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.6

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install pipx
          pipx ensurepath
          pipx install poetry

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::246770851643:role/github-actions
          aws-region: eu-central-1

      - name: Build layers and packages
        run: |
          cd backend && make build

      - name: deploy terraform
        env:
          TF_VAR_openai_api_key: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cd backend && ./deploy.sh dev

  smoke_test:
    needs: deploy_dev_infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::246770851643:role/github-actions
          aws-region: eu-central-1

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.6

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install pipx
          pipx ensurepath
          pipx install poetry

      - name: Smoke test
        env:
          API_GATEWAY_HOST: ${{ secrets.API_GATEWAY_HOST }}
        run: |
          pushd shared
          poetry install --with dev
          make smoketest

  deploy_prod:
    needs: smoke_test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::246770851643:role/github-actions
          aws-region: eu-central-1

      - name: Deploy prod
        env:
          TF_VAR_openai_api_key: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cd backend && ./deploy.sh prod