name: Docker Image CI

permissions:
  contents: read
  id-token: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install pipx
          pipx ensurepath
          pipx install poetry

      - name: set up backend
        run: |
          cd backend && poetry install --with dev --with nlp --with generative
          make test
          
      - name: set up shared
        run: |
          cd shared && poetry install --with dev
          make test

      - name: Build layers and packages
        run: |
          pushd backend
          ./build-deps generative
          make generative-lambda

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::246770851643:role/github-actions
          aws-region: eu-central-1
      
      - name: Create infrastructure
        run: |
          pushd backend/terraform
          terraform apply -auto-approve