name: Docker Image CI

permissions:
  contents: read
  id-token: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.6

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install pipx
          pipx ensurepath
          pipx install poetry

      - name: set up backend
        run: |
          cd backend && poetry install --with dev --with nlp --with generative
          make test

      - name: set up shared
        run: |
          cd shared && poetry install --with dev
          make test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::246770851643:role/github-actions
          aws-region: eu-central-1

      - name: Build layers and packages
        run: |
          pushd backend
          ./build-deps.sh generative
          make build-lambda

      - name: Build syntactical_analysis docker image
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          pushd backend
          ./docker-util.sh build syntactical_analysis dev
          ./docker-util.sh push syntactical_analysis dev

      - name: Create dev environment
        env:
          TF_VAR_openai_api_key: ${{ secrets.OPENAI_API_KEY }}
        run: |
          ./deploy.sh dev

      - name: Smoke test
        env:
          API_GATEWAY_URL: ${{ secrets.API_GATEWAY_URL }}
        run: |
          cd shared && make smoke-test